<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket",
	"main",
	array(
		"ACTION_VARIABLE" => "basketAction",
		"ADDITIONAL_PICT_PROP_1" => "-",
		"ADDITIONAL_PICT_PROP_4" => "-",
		"AUTO_CALCULATION" => "Y",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
			6 => "PROPERTY_TSVET",
			7 => "PROPERTY_RAZMER",
			8 => "PROPERTY_BREND",
		),
		"COLUMNS_LIST_MOBILE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
			6 => "PROPERTY_TSVET",
			7 => "PROPERTY_RAZMER",
			8 => "PROPERTY_BREND",
		),
		"COMPATIBLE_MODE" => "Y",
		"CORRECT_RATIO" => "Y",
		"DEFERRED_REFRESH" => "N",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"DISPLAY_MODE" => "extended",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"HIDE_COUPON" => "N",
		"LABEL_PROP" => array(
		),
		"OFFERS_PROPS" => array(
		),
		"PATH_TO_ORDER" => "/personal/order/make/",
		"PRICE_DISPLAY_MODE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
		"QUANTITY_FLOAT" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_FILTER" => "Y",
		"SHOW_RESTORE" => "Y",
		"TEMPLATE_THEME" => "blue",
		"TOTAL_BLOCK_DISPLAY" => array(
			0 => "bottom",
		),
		"USE_DYNAMIC_SCROLL" => "Y",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_GIFTS" => "Y",
		"USE_PREPAYMENT" => "N",
		"USE_PRICE_ANIMATION" => "Y",
		"COMPONENT_TEMPLATE" => ".default"
	),
	false
);?><br>

<?$APPLICATION->IncludeComponent(
    "kreattika:sale.oneclickbuy",
    "",
    array(
        "COMPONENT_TEMPLATE" => "",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "FORM_ID" => "us3fqlvkkmaf9r54ccj3",
        "FORM_TITLE" => "Заказ в 1 клик",
        "USE_CAPTCHA" => "N",
        "SUBMIT_TITLE" => "Оформить заказ",
        "SUCCESS_TEXT" => "Заказ #ORDER_ID# создан. Наши менеджеры свяжутся с Вами в самое ближайшее время. Удачного дня.",
        "EMAIL_TO" => "spirit_dim@inbox.ru",
        "EVENT_MESSAGE_TYPE" => "KREATTIKA_SALE_ONE_CLICK_BUY",
        "EVENT_MESSAGE_ID" => array(
        ),
        "USE_FIELDS" => array(
            0 => "NAME",
            1 => "PHONE",
        ),
        "SHOW_ERRORS" => "Y",
        "USE_USER_CONSENT" => "N",
        "SET_YANDEX_METRIKA_GOAL" => "N",
        "PERSON_TYPE_VIEWTYPE" => "VALUE",
        "PERSON_TYPE_ID" => $_REQUEST["PERSON_TYPE_ID"],
        "DELIVERY_VIEWTYPE" => "VALUE",
        "DELIVERY_ID" => 2,
        "PAY_SYSTEM_VIEWTYPE" => "VALUE",
        "PAY_SYSTEM_ID" => 2,
        "CURRENCY_VIEWTYPE" => "BASE_CURRENCY",
        "ORDER_STATUS_VIEWTYPE" => "VALUE",
        "ORDER_STATUS_ID" => $_REQUEST["ORDER_STATUS_ID"],
        "ORDER_COMMENT" => "Купить в 1 клик",
        "BUY_ALL_BASKET" => "Y",
        "FIELD_NAME_LABEL" => "Имя",
        "FIELD_NAME_PLACEHOLDER" => "Имя",
        "FIELD_NAME_CHECK" => "Y",
        "FIELD_NAME_LINK_ORDER_PROPERTY" => "",
        "FIELD_PHONE_LABEL" => "Телефон",
        "FIELD_PHONE_PLACEHOLDER" => "Телефон",
        "FIELD_PHONE_CHECK" => "Y",
        "FIELD_PHONE_LINK_ORDER_PROPERTY" => ""
    ),
    false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
