<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");

?><?$APPLICATION->IncludeComponent(
	"kreattika:sale.oneclickbuy", 
	"bootstrap", 
	array(
		"COMPONENT_TEMPLATE" => "bootstrap",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"FORM_ID" => "us3fqlvkkmaf9r54ccj3",
		"FORM_TITLE" => "Заказ в 1 клик",
		"USE_CAPTCHA" => "N",
		"SUBMIT_TITLE" => "Оформить заказ",
		"SUCCESS_TEXT" => "Заказ #ORDER_ID# создан. Наши менеджеры свяжутся с Вами в самое ближайшее время. Удачного дня.",
		"EMAIL_TO" => "EMAIL",
		"EVENT_MESSAGE_TYPE" => "KREATTIKA_SALE_ONE_CLICK_BUY",
		"EVENT_MESSAGE_ID" => array(
			0 => "91",
		),
		"USE_FIELDS" => array(
			0 => "NAME",
			1 => "PHONE",
		),
		"SHOW_ERRORS" => "Y",
		"USE_USER_CONSENT" => "N",
		"SET_YANDEX_METRIKA_GOAL" => "N",
		"PERSON_TYPE_VIEWTYPE" => "VALUE",
		"PERSON_TYPE_ID" => "1",
		"DELIVERY_VIEWTYPE" => "VALUE",
		"DELIVERY_ID" => "1",
		"PAY_SYSTEM_VIEWTYPE" => "VALUE",
		"PAY_SYSTEM_ID" => "3",
		"CURRENCY_VIEWTYPE" => "BASE_CURRENCY",
		"ORDER_STATUS_VIEWTYPE" => "VALUE",
		"ORDER_STATUS_ID" => $_REQUEST["ORDER_STATUS_ID"],
		"ORDER_COMMENT" => "Купить в 1 клик",
		"BUY_ALL_BASKET" => "N",
		"FIELD_NAME_LABEL" => "Имя",
		"FIELD_NAME_PLACEHOLDER" => "Имя",
		"FIELD_NAME_CHECK" => "Y",
		"FIELD_NAME_LINK_ORDER_PROPERTY" => "FIO",
		"FIELD_PHONE_LABEL" => "Телефон",
		"FIELD_PHONE_PLACEHOLDER" => "Телефон",
		"FIELD_PHONE_CHECK" => "Y",
		"FIELD_PHONE_LINK_ORDER_PROPERTY" => "FIO",
		"FIELD_EMAIL_LABEL" => "E-mail",
		"FIELD_EMAIL_PLACEHOLDER" => "E-mail",
		"FIELD_EMAIL_CHECK" => "Y",
		"FIELD_EMAIL_LINK_ORDER_PROPERTY" => "FIO",
		"FIELD_ADDRESS_LABEL" => "Адрес доставки заказа",
		"FIELD_ADDRESS_PLACEHOLDER" => "Адрес доставки заказа",
		"FIELD_ADDRESS_CHECK" => "Y",
		"FIELD_ADDRESS_LINK_ORDER_PROPERTY" => "FIO",
		"FIELD_COMMENT_LABEL" => "Комментарий к заказу",
		"FIELD_COMMENT_PLACEHOLDER" => "Комментарий к заказу",
		"FIELD_COMMENT_CHECK" => "Y",
		"PRODUCT_ID" => $_REQUEST["PRODUCT_ID"],
		"PRODUCT_QUANTITY_DEFAULT_VALUE" => $_REQUEST["PRODUCT_QUANTITY"],
		"PRODUCT_QUANTITY_CHECK_STORE" => "N",
		"PRODUCT_CUSTOM_PRICE" => "N"
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
